name: 'Hugo setup'
description: 'GitHub Actions for Hugo ⚡️ Setup Hugo quickly and build your site fast. Hugo extended and Hugo Modules are supported.'
author: 'peaceiris'

branding:
  icon: package
  color: yellow

inputs:
  hugo-version:
    description: 'The Hugo version to use (if not latest). Example: 0.58.2'
    required: false
    default: latest
  extended:
    description: 'Use Hugo extended version (default false). Example: true'
    required: false
    default: 'false'

runs:
  using: node20
  main: dist/index.js
